// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI;

namespace WebAPI.Migrations
{
    [DbContext(typeof(DBInteractor))]
    [Migration("20210417204643_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("WebAPI.Models.Toy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Toy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jack in the Box",
                            Price = 999
                        },
                        new
                        {
                            Id = 2,
                            Name = "Buzz Lightyear",
                            Price = 2499
                        },
                        new
                        {
                            Id = 3,
                            Name = "Etch-A-Sketch",
                            Price = 1998
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
